# 以Deployment部署Pod
# vi springboot-demo.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-demo
spec:
  selector:
    matchLabels:
      app: springboot-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-demo
    spec:
      containers:
        - name: springboot-demo
          image: build_docker_0 # 记得改
          imagePullPolicy: Never
          ports:
            - containerPort: 18080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  type: NodePort
  ports:
    - port: 18080
      targetPort: 18080
      protocol: TCP
      nodePort: 30080
  selector:
    app: springboot-demo
